name: unittest
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: ProjectCheckout
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: build
      run: mkdir build && cd build && cmake .. && make && ./Testsdtp
